In [1]:
import pandas as pd
#loading the three seperate csv files
orders_df = pd.read_csv("olist_orders_dataset.csv")
payments_df = pd.read_csv("olist_order_payments_dataset.csv")
items_df = pd.read_csv("olist_order_items_dataset.csv")

print(orders_df['order_status'].value_counts())

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [2]:
payments_df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [3]:
#merging the first two files using an inner join based on shared key order_id
merged_step1 = pd.merge(orders_df,payments_df, on= 'order_id',how='left' )

In [4]:
merged_step1.tail(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
103882,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,1.0,credit_card,3.0,85.08
103883,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,credit_card,3.0,195.00
103884,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,credit_card,5.0,271.01
103885,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,credit_card,4.0,441.16
103886,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,debit_card,1.0,86.86

In [5]:
#merge the items csv with the merged one as same as above
master_df = pd.merge(merged_step1,items_df,on="order_id",how="left")
items_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
master_df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,credit_card,1.0,18.12,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,3.0,voucher,1.0,2.00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2.0,voucher,1.0,18.59,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,boleto,1.0,141.46,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,credit_card,3.0,179.12,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22

In [7]:
print("=== STEP 1: DATA MERGING COMPLETE ===")
print(f"Total rows in combined dataset: {master_df.shape[0]}")
print(f"Total columns available for analysis: {master_df.shape[1]}")

=== STEP 1: DATA MERGING COMPLETE ===
Total rows in combined dataset: 118434
Total columns available for analysis: 18

In [8]:
master_df.dtypes

order_id                          object
customer_id                       object
order_status                      object
order_purchase_timestamp          object
order_approved_at                 object
order_delivered_carrier_date      object
order_delivered_customer_date     object
order_estimated_delivery_date     object
payment_sequential               float64
payment_type                      object
payment_installments             float64
payment_value                    float64
order_item_id                    float64
product_id                        object
seller_id                         object
shipping_limit_date               object
price                            float64
freight_value                    float64
dtype: object

In [9]:
filtered_df = master_df[
    master_df['order_status'].isin(['cancelled', 'unavailable'])
]
filtered_df.shape

(650, 18)

In [10]:
master_df.describe()

,payment_sequential,payment_installments,payment_value,order_item_id,price,freight_value
count,118431.000000,118431.000000,118431.000000,117604.000000,117604.000000,117604.000000
mean,1.094207,2.937398,172.849395,1.195920,120.822849,20.045551
std,0.728290,2.774164,268.259831,0.697721,184.477367,15.861351
min,1.000000,0.000000,0.000000,1.000000,0.850000,0.000000
25%,1.000000,1.000000,60.860000,1.000000,39.900000,13.080000
50%,1.000000,2.000000,108.200000,1.000000,74.900000,16.290000
75%,1.000000,4.000000,189.245000,1.000000,134.900000,21.190000
max,29.000000,24.000000,13664.080000,21.000000,6735.000000,409.680000

In [11]:
#creating a new column "is_cancelled" filled with 0's and 1's

master_df['is_cancelled'] = master_df['order_status'].apply(lambda x: 1 if x in ['cancelled','unavailable'] else 0) 

master_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,is_cancelled
86187,5c3353d0e879379685e40fcfee970725,3367650082744b78bf5f60819c438960,delivered,2018-01-11 19:09:09,2018-01-13 04:54:50,2018-01-16 22:28:39,2018-01-25 22:09:45,2018-02-08 00:00:00,1.0,boleto,1.0,316.26,2.0,64e054669023deb2bfa82f61a2829404,da8622b14eb17ae2831f4ac5b9dab84a,2018-01-18 02:31:29,139.90,18.23,0
104392,53d9e9ca11320965aa55056b5439a1c5,b495f4cb5075ba6f945da71e64575cc6,delivered,2018-03-27 13:54:14,2018-03-27 14:07:56,2018-03-29 01:08:43,2018-04-14 13:21:28,2018-04-11 00:00:00,1.0,credit_card,8.0,88.90,1.0,363218ba55c610b750224f90bdd34be1,33a6f4b1e7cdc205511e76ba1b6e0186,2018-04-04 14:07:56,79.99,8.91,0
19581,c5f0b9e8bd23e3d37855d76739573355,2d168556d327700dc590e84a3b12112d,delivered,2018-02-05 17:50:38,2018-02-05 18:50:35,2018-02-08 22:32:27,2018-02-20 21:55:22,2018-03-06 00:00:00,1.0,credit_card,3.0,76.08,1.0,de1eee6c50298db6028af08bd88a702a,994f04b3718c2bab35c2adfa8afecd2a,2018-02-09 18:50:35,59.90,16.18,0
941,4ef04edb491b8cc23eabe782ced6715c,5db7793e5ba9211bf9e8176cb8bb3ecf,delivered,2018-01-19 09:51:37,2018-01-20 12:51:00,2018-01-22 21:25:00,2018-01-31 18:33:28,2018-02-14 00:00:00,1.0,credit_card,1.0,84.24,1.0,980f472a1354c8366960f7c4528c470e,06a2c3af7b3aee5d69171b0e14f0ee87,2018-01-25 12:51:00,56.99,27.25,0
112891,b9230771a7ecccb578891ecdf1879527,43de4c514a47351d1496f50f85c44f29,delivered,2017-11-24 06:17:37,2017-11-25 04:53:21,2017-11-28 20:21:50,2017-12-19 17:09:27,2017-12-15 00:00:00,1.0,boleto,1.0,52.01,1.0,9a00058f48982cd587fccba20c2bdaf7,f8db351d8c4c4c22c6835c19a46f01b0,2017-11-30 04:53:21,35.90,16.11,0

In [12]:
#select only the columns we need for analysis to keep things clean

cleaned_df = master_df[['is_cancelled', 'price', 'freight_value', 'payment_installments']].copy()
cleaned_df.head()

   is_cancelled   price  freight_value  payment_installments
0             0   29.99           8.72                   1.0
1             0   29.99           8.72                   1.0
2             0   29.99           8.72                   1.0
3             0  118.70          22.76                   1.0
4             0  159.90          19.22                   3.0

In [13]:
cleaned_df['price'] = cleaned_df['price'].fillna(0)
cleaned_df['freight_value'] = cleaned_df['freight_value'].fillna(0)
cleaned_df['payment_installments'] = cleaned_df['payment_installments'].fillna(1)

In [14]:
cleaned_df.shape

(118434, 4)

In [15]:
#dropping the null rows so that our model doesn't crashes later

cleaned_df = cleaned_df.dropna()
cleaned_df.shape

(118434, 4)

In [16]:

print("=== STEP 2: MAPPING AND CLEANING COMPLETE ===")
print("Breakdown of Scheduled Deliveries (0) vs. Canceled Revenue Losses (1):")
print(cleaned_df['is_cancelled'].value_counts())

=== STEP 2: MAPPING AND CLEANING COMPLETE ===
Breakdown of Scheduled Deliveries (0) vs. Canceled Revenue Losses (1):
is_cancelled
0    117784
1       650
Name: count, dtype: int64

In [17]:
eda_summary  = cleaned_df.groupby('is_cancelled')[['price','payment_installments']].mean()

In [18]:
print("=== STEP 3: EXPLORATORY DATA ANALYSIS ===")
print("Average values for Completed (0) vs Canceled (1) orders:")
eda_summary

=== STEP 3: EXPLORATORY DATA ANALYSIS ===
Average values for Completed (0) vs Canceled (1) orders:

                   price  payment_installments
is_cancelled
0             120.621159              2.938336
1               3.088754              2.758462

In [19]:
print("I discovered that canceled orders have a shockingly low average price of 3.08 compared to completed orders at 120.62. This means people aren't dropping out because of high prices. Instead, they are likely abandoning very cheap items—potentially because the shipping fees (freight cost) are much higher than the item itself, making the purchase illogical!")

I discovered that canceled orders have a shockingly low average price of 3.08 compared to completed orders at 120.62. This means people aren't dropping out because of high prices. Instead, they are likely abandoning very cheap items—potentially because the shipping fees (freight cost) are much higher than the item itself, making the purchase illogical!

In [20]:
import sklearn

In [21]:
# Step 4:Training the machine learning model

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#defining our inputs(X) and what we want to predict(y)
X = cleaned_df[['price','freight_value','payment_installments']]
y = cleaned_df['is_cancelled']

#split the data into 80% for training the model and 20% to test its memory
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 42)


scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

#intialize the logistic regression model
#we use class weight = 'balanced' because we have more 0's than 1's

model = LogisticRegression()

#Train the model
model = model.fit(X_train,y_train)


#Test the model
y_pred = model.predict(X_test)

print("=== STEP 4: MACHINE LEARNING MODEL TRAINED ===")
print(f"Model Training Accuracy Score: {accuracy_score(y_test, y_pred) * 100:.2f}%")
pred_df = X_test.copy()

pred_df['y_pred'] = y_pred

print(pred_df.head())

=== STEP 4: MACHINE LEARNING MODEL TRAINED ===
Model Training Accuracy Score: 99.83%
         price  freight_value  payment_installments  y_pred
59764    29.90          15.23                   4.0       0
117039   14.97          14.52                   3.0       0
21165    78.00          12.89                   1.0       0
17269    57.99          15.62                   3.0       0
39896   188.00          23.03                   1.0       0

In [23]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     23554
           1       0.77      0.98      0.86       133

    accuracy                           1.00     23687
   macro avg       0.89      0.99      0.93     23687
weighted avg       1.00      1.00      1.00     23687

In [24]:
new_orders = [
    [1, 0, 1],          # ultra cheap, free shipping
    [9999, 500, 24],    # extremely expensive + huge freight
    [15000, 1000, 36],  # very extreme
    [5, 300, 12],       # cheap product but huge shipping
    [2000, 5, 1],       # expensive but tiny freight
    [50, 800, 48],      # impossible-looking order
    [7000, 1500, 60],   # very risky-looking order
    [20, 0, 24],        # tiny price with many installments
]

predictions = model.predict(new_orders)


print(predictions)

[1 0 0 0 0 0 0 0]

C:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [25]:
probs = model.predict_proba(new_orders)[:,1]

custom_pred = (probs > 0.2).astype(int)

print(custom_pred)

[1 0 0 0 0 0 0 1]

C:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [26]:
new_orders = [
    [3, 44, 45],
    [9999, 500, 24],
    [50, 800, 48]
]
new_orders_scaled = scaler.transform(new_orders)

predictions = model.predict(new_orders_scaled)

probabilities = model.predict_proba(new_orders_scaled)

print(predictions)

print(probabilities)

[0 0 0]
[[5.09520355e-01 4.90479645e-01]
 [1.00000000e+00 3.48261360e-12]
 [1.00000000e+00 2.09948697e-16]]

C:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [27]:
import pickle

# 1. Save the trained Logistic Regression model to a permanent file
with open('logistic_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

# 2. Save the Standard Scaler object to a permanent file
# (Replace 'scaler' with the exact variable name you used for your StandardScaler)
with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)

print("=== STEP 1 COMPLETE: Model and Scaler exported safely! ===")

=== STEP 1 COMPLETE: Model and Scaler exported safely! ===